#!/bin/bash

dir=$1

[ -z $dir ] && echo "missing repo dir" && exit 1

cd $dir
localBranch=$(git branch --show-current)
remoteBranch=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})

echo "checking $dir"
git remote update >/dev/null

localHash=$(git rev-parse $localBranch)
remoteHash=$(git rev-parse $remoteBranch)

if [ $localHash != $remoteHash ]; then
  echo "publishing $dir $remoteHash"
  git pull --rebase
  yarn
  pm2 reload pm2.json
fi
